"""chemsplit: dataset-splitting strategies for cheminformatics machine learning.
"""

from __future__ import annotations

import importlib
from typing import TYPE_CHECKING, Any

__version__ = "0.1.0"

if TYPE_CHECKING:
    # Static-only; __getattr__ below resolves these lazily at runtime.
    from chemsplit.audit import (
        LeakageReport,
        adversarial_validation,
        audit_split,
        nn_similarity_profile,
        y_scramble_control,
    )
    from chemsplit.base import BaseSplitter, GroupSplitter, SplitResult, Strictness
    from chemsplit.exceptions import (
        ChemSplitError,
        ChemSplitWarning,
        CircularityWarning,
        ColumnError,
        ConfigurationError,
        ConstraintUnsatisfiableError,
        DegenerateClusterWarning,
        DegenerateGroupingError,
        DeterminismWarning,
        DuplicateRecordError,
        DuplicateWarning,
        EmptyInputError,
        EmptyPartitionError,
        HomologyLeakWarning,
        InfeasibleSplitError,
        InputError,
        InputKindError,
        InvariantError,
        LabelError,
        MissingDependencyError,
        MoleculeParseError,
        ParameterError,
        ParseWarning,
        ScalabilityError,
        SizeToleranceWarning,
        SmallPartitionWarning,
        StandardizationWarning,
        UnknownFeaturizerError,
        UnknownMetricError,
        UnknownSplitterError,
    )
    from chemsplit.featurizers import Featurizer, get_featurizer
    from chemsplit.registry import SPLITTER_REGISTRY, get_splitter, list_splitters
    from chemsplit.splitters.baseline import (
        KFoldSplitter,
        MonteCarloSplitter,
        PredefinedSplitter,
        RandomSplitter,
        StratifiedRandomSplitter,
    )
    from chemsplit.splitters.biomolecular import (
        BindingSiteSplitter,
        ComplexJointSplitter,
        DepositionDateSplitter,
        ProteinFamilySplitter,
        SequenceIdentitySplitter,
    )
    from chemsplit.splitters.embedding import (
        LatentSpaceSplitter,
        ProjectionSplitter,
        SelfOrganizingMapSplitter,
        UMAPClusterSplitter,
    )
    from chemsplit.splitters.lineage import (
        FidelitySplitter,
        PartySplitter,
        SIMPDSplitter,
        SourceSplitter,
        TemporalSplitter,
    )
    from chemsplit.splitters.property_ import (
        AdversarialSplitter,
        DistinctLabelSplitter,
        LabelExtrapolationSplitter,
        MOODSplitter,
        PropertySplitter,
        StratifiedDistributionSplitter,
    )
    from chemsplit.splitters.protocol import (
        ApplicabilityDomainSplitter,
        ExternalHoldoutSplitter,
        GroupKFoldSplitter,
        IntersectionSplitter,
        NestedCVSplitter,
        RepeatedSplitter,
        ThreeWaySplitter,
    )
    from chemsplit.splitters.scaffold import (
        ActivityCliffSplitter,
        GenericScaffoldSplitter,
        MatchedMolecularSeriesSplitter,
        MurckoScaffoldSplitter,
        RingSystemSplitter,
        ScaffoldTreeSplitter,
        SubstructureSplitter,
    )
    from chemsplit.splitters.similarity import (
        BalancedMultiTaskSplitter,
        ButinaSplitter,
        DensityClusterSplitter,
        DOptimalSplitter,
        DuplexSplitter,
        KMeansClusterSplitter,
        LeaveOneClusterOutSplitter,
        MaxDissimilaritySplitter,
        MaxMinSplitter,
        MinimalTestSetDissimilaritySplitter,
        OptiSimSplitter,
        PerimeterSplitter,
        SimilarityThresholdSplitter,
        SpectralSplitter,
        SphereExclusionSplitter,
        SPXYSplitter,
        SupportPointsSplitter,
    )
    from chemsplit.splitters.task import (
        AVESplitter,
        ColdDrugSplitter,
        ColdPairSplitter,
        ColdTargetSplitter,
        DecoyBenchmarkSplitter,
        HiSplitter,
        LoSplitter,
        ScaffoldHopSplitter,
    )

__all__ = [
    # -- 64 splitters across 9 families, in declared order: baseline (5), scaffold (7),
    # similarity (17), embedding (4), property (6), lineage (5), task (8), biomolecular (5),
    # protocol (7) --
    "RandomSplitter",
    "StratifiedRandomSplitter",
    "KFoldSplitter",
    "MonteCarloSplitter",
    "PredefinedSplitter",
    "MurckoScaffoldSplitter",
    "GenericScaffoldSplitter",
    "ScaffoldTreeSplitter",
    "RingSystemSplitter",
    "SubstructureSplitter",
    "MatchedMolecularSeriesSplitter",
    "ActivityCliffSplitter",
    "SimilarityThresholdSplitter",
    "ButinaSplitter",
    "SphereExclusionSplitter",
    "KMeansClusterSplitter",
    "DensityClusterSplitter",
    "SpectralSplitter",
    "MaxMinSplitter",
    "SPXYSplitter",
    "OptiSimSplitter",
    "MinimalTestSetDissimilaritySplitter",
    "SupportPointsSplitter",
    "DuplexSplitter",
    "DOptimalSplitter",
    "MaxDissimilaritySplitter",
    "PerimeterSplitter",
    "LeaveOneClusterOutSplitter",
    "BalancedMultiTaskSplitter",
    "UMAPClusterSplitter",
    "ProjectionSplitter",
    "SelfOrganizingMapSplitter",
    "LatentSpaceSplitter",
    "PropertySplitter",
    "LabelExtrapolationSplitter",
    "DistinctLabelSplitter",
    "StratifiedDistributionSplitter",
    "MOODSplitter",
    "AdversarialSplitter",
    "TemporalSplitter",
    "SIMPDSplitter",
    "SourceSplitter",
    "FidelitySplitter",
    "PartySplitter",
    "HiSplitter",
    "LoSplitter",
    "ScaffoldHopSplitter",
    "ColdDrugSplitter",
    "ColdTargetSplitter",
    "ColdPairSplitter",
    "AVESplitter",
    "DecoyBenchmarkSplitter",
    "SequenceIdentitySplitter",
    "ProteinFamilySplitter",
    "BindingSiteSplitter",
    "DepositionDateSplitter",
    "ComplexJointSplitter",
    "GroupKFoldSplitter",
    "ThreeWaySplitter",
    "RepeatedSplitter",
    "NestedCVSplitter",
    "ExternalHoldoutSplitter",
    "ApplicabilityDomainSplitter",
    "IntersectionSplitter",
    # core types
    "BaseSplitter",
    "GroupSplitter",
    "SplitResult",
    "Strictness",
    # registry
    "get_splitter",
    "list_splitters",
    "SPLITTER_REGISTRY",
    # audit
    "audit_split",
    "LeakageReport",
    "adversarial_validation",
    "nn_similarity_profile",
    "y_scramble_control",
    # featurizers
    "get_featurizer",
    "Featurizer",
    # exceptions
    "ChemSplitError",
    "ParameterError",
    "ConfigurationError",
    "UnknownSplitterError",
    "UnknownFeaturizerError",
    "UnknownMetricError",
    "InputError",
    "InputKindError",
    "ColumnError",
    "EmptyInputError",
    "MoleculeParseError",
    "DuplicateRecordError",
    "LabelError",
    "InfeasibleSplitError",
    "DegenerateGroupingError",
    "ConstraintUnsatisfiableError",
    "EmptyPartitionError",
    "ScalabilityError",
    "MissingDependencyError",
    "InvariantError",
    # warnings
    "ChemSplitWarning",
    "SizeToleranceWarning",
    "DuplicateWarning",
    "ParseWarning",
    "StandardizationWarning",
    "DeterminismWarning",
    "DegenerateClusterWarning",
    "SmallPartitionWarning",
    "CircularityWarning",
    "HomologyLeakWarning",
    "__version__",
]

# name -> the submodule that defines it; anything missing falls through to AttributeError in
# __getattr__. chemsplit.featurizers and chemsplit.exceptions are listed too, even though they
# import no rdkit or sklearn at module scope and so would be cheap to import eagerly.
_LAZY_SOURCE: dict[str, str] = {
    "RandomSplitter": "chemsplit.splitters.baseline",
    "StratifiedRandomSplitter": "chemsplit.splitters.baseline",
    "KFoldSplitter": "chemsplit.splitters.baseline",
    "MonteCarloSplitter": "chemsplit.splitters.baseline",
    "PredefinedSplitter": "chemsplit.splitters.baseline",
    "MurckoScaffoldSplitter": "chemsplit.splitters.scaffold",
    "GenericScaffoldSplitter": "chemsplit.splitters.scaffold",
    "ScaffoldTreeSplitter": "chemsplit.splitters.scaffold",
    "RingSystemSplitter": "chemsplit.splitters.scaffold",
    "SubstructureSplitter": "chemsplit.splitters.scaffold",
    "MatchedMolecularSeriesSplitter": "chemsplit.splitters.scaffold",
    "ActivityCliffSplitter": "chemsplit.splitters.scaffold",
    "SimilarityThresholdSplitter": "chemsplit.splitters.similarity",
    "ButinaSplitter": "chemsplit.splitters.similarity",
    "SphereExclusionSplitter": "chemsplit.splitters.similarity",
    "KMeansClusterSplitter": "chemsplit.splitters.similarity",
    "DensityClusterSplitter": "chemsplit.splitters.similarity",
    "SpectralSplitter": "chemsplit.splitters.similarity",
    "MaxMinSplitter": "chemsplit.splitters.similarity",
    "SPXYSplitter": "chemsplit.splitters.similarity",
    "OptiSimSplitter": "chemsplit.splitters.similarity",
    "MinimalTestSetDissimilaritySplitter": "chemsplit.splitters.similarity",
    "SupportPointsSplitter": "chemsplit.splitters.similarity",
    "DuplexSplitter": "chemsplit.splitters.similarity",
    "DOptimalSplitter": "chemsplit.splitters.similarity",
    "MaxDissimilaritySplitter": "chemsplit.splitters.similarity",
    "PerimeterSplitter": "chemsplit.splitters.similarity",
    "LeaveOneClusterOutSplitter": "chemsplit.splitters.similarity",
    "BalancedMultiTaskSplitter": "chemsplit.splitters.similarity",
    "UMAPClusterSplitter": "chemsplit.splitters.embedding",
    "ProjectionSplitter": "chemsplit.splitters.embedding",
    "SelfOrganizingMapSplitter": "chemsplit.splitters.embedding",
    "LatentSpaceSplitter": "chemsplit.splitters.embedding",
    "PropertySplitter": "chemsplit.splitters.property_",
    "LabelExtrapolationSplitter": "chemsplit.splitters.property_",
    "DistinctLabelSplitter": "chemsplit.splitters.property_",
    "StratifiedDistributionSplitter": "chemsplit.splitters.property_",
    "MOODSplitter": "chemsplit.splitters.property_",
    "AdversarialSplitter": "chemsplit.splitters.property_",
    "TemporalSplitter": "chemsplit.splitters.lineage",
    "SIMPDSplitter": "chemsplit.splitters.lineage",
    "SourceSplitter": "chemsplit.splitters.lineage",
    "FidelitySplitter": "chemsplit.splitters.lineage",
    "PartySplitter": "chemsplit.splitters.lineage",
    "HiSplitter": "chemsplit.splitters.task",
    "LoSplitter": "chemsplit.splitters.task",
    "ScaffoldHopSplitter": "chemsplit.splitters.task",
    "ColdDrugSplitter": "chemsplit.splitters.task",
    "ColdTargetSplitter": "chemsplit.splitters.task",
    "ColdPairSplitter": "chemsplit.splitters.task",
    "AVESplitter": "chemsplit.splitters.task",
    "DecoyBenchmarkSplitter": "chemsplit.splitters.task",
    "SequenceIdentitySplitter": "chemsplit.splitters.biomolecular",
    "ProteinFamilySplitter": "chemsplit.splitters.biomolecular",
    "BindingSiteSplitter": "chemsplit.splitters.biomolecular",
    "DepositionDateSplitter": "chemsplit.splitters.biomolecular",
    "ComplexJointSplitter": "chemsplit.splitters.biomolecular",
    "GroupKFoldSplitter": "chemsplit.splitters.protocol",
    "ThreeWaySplitter": "chemsplit.splitters.protocol",
    "RepeatedSplitter": "chemsplit.splitters.protocol",
    "NestedCVSplitter": "chemsplit.splitters.protocol",
    "ExternalHoldoutSplitter": "chemsplit.splitters.protocol",
    "ApplicabilityDomainSplitter": "chemsplit.splitters.protocol",
    "IntersectionSplitter": "chemsplit.splitters.protocol",
    "BaseSplitter": "chemsplit.base",
    "GroupSplitter": "chemsplit.base",
    "SplitResult": "chemsplit.base",
    "Strictness": "chemsplit.base",
    "get_splitter": "chemsplit.registry",
    "list_splitters": "chemsplit.registry",
    "SPLITTER_REGISTRY": "chemsplit.registry",
    "audit_split": "chemsplit.audit",
    "LeakageReport": "chemsplit.audit",
    "adversarial_validation": "chemsplit.audit",
    "nn_similarity_profile": "chemsplit.audit",
    "y_scramble_control": "chemsplit.audit",
    "get_featurizer": "chemsplit.featurizers",
    "Featurizer": "chemsplit.featurizers",
    "ChemSplitError": "chemsplit.exceptions",
    "ParameterError": "chemsplit.exceptions",
    "ConfigurationError": "chemsplit.exceptions",
    "UnknownSplitterError": "chemsplit.exceptions",
    "UnknownFeaturizerError": "chemsplit.exceptions",
    "UnknownMetricError": "chemsplit.exceptions",
    "InputError": "chemsplit.exceptions",
    "InputKindError": "chemsplit.exceptions",
    "ColumnError": "chemsplit.exceptions",
    "EmptyInputError": "chemsplit.exceptions",
    "MoleculeParseError": "chemsplit.exceptions",
    "DuplicateRecordError": "chemsplit.exceptions",
    "LabelError": "chemsplit.exceptions",
    "InfeasibleSplitError": "chemsplit.exceptions",
    "DegenerateGroupingError": "chemsplit.exceptions",
    "ConstraintUnsatisfiableError": "chemsplit.exceptions",
    "EmptyPartitionError": "chemsplit.exceptions",
    "ScalabilityError": "chemsplit.exceptions",
    "MissingDependencyError": "chemsplit.exceptions",
    "InvariantError": "chemsplit.exceptions",
    "ChemSplitWarning": "chemsplit.exceptions",
    "SizeToleranceWarning": "chemsplit.exceptions",
    "DuplicateWarning": "chemsplit.exceptions",
    "ParseWarning": "chemsplit.exceptions",
    "StandardizationWarning": "chemsplit.exceptions",
    "DeterminismWarning": "chemsplit.exceptions",
    "DegenerateClusterWarning": "chemsplit.exceptions",
    "SmallPartitionWarning": "chemsplit.exceptions",
    "CircularityWarning": "chemsplit.exceptions",
    "HomologyLeakWarning": "chemsplit.exceptions",
}


def __getattr__(name: str) -> Any:
    if name == "__version__":
        return __version__
    source = _LAZY_SOURCE.get(name)
    if source is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = importlib.import_module(source)
    value = getattr(module, name)
    globals()[name] = value  # cache on the package module so repeat access is free
    return value


def __dir__() -> list[str]:
    return sorted(__all__)
